language: csharp
solution: DevTree.Mvvm.sln
mono: none
dotnet: 1.0.0
dist: trusty

script:
 - dotnet restore
 - dotnet build -c Release
 - dotnet nuget push src\DevTree.Mvvin\Debug\*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --verbosity detailed
